// Executable forms (.claude/**) are rendered once, from the kit's own copies.
// Rendering is mechanical: rewrite the paths the kit names, then state the
// project's facts in one clearly-marked block. Prose is never rewritten.
import { posix } from 'node:path';
import { dest } from './manifest.mjs';

const BLOCK = '## Project context (generated by devos install — edit freely, never regenerated)';

/**
 * `.claude/` must sit at the repo root while the kit sits in a subdirectory, so a link
 * written as `../.claude/commands/` is one level short once installed. Recompute those
 * targets against the real layout; links that stay inside the kit are already correct
 * and are left byte-identical.
 */
export function relink(text, { path, config, manifest }) {
  const fromDir = posix.dirname(path);
  const toDir = posix.dirname(dest(path, config, manifest));

  const moved = (target) => {
    const kitPath = posix.normalize(posix.join(fromDir, target));
    const bare = kitPath.replace(/\/$/, '');
    if (bare === '.claude' || bare.startsWith('.claude/')) {
      return bare.replace(/^\.claude/, config.claudeDir) + (target.endsWith('/') ? '/' : '');
    }
    if (bare === 'board' || bare.startsWith('board/')) {
      return bare.replace(/^board/, config.boardDir) + (target.endsWith('/') ? '/' : '');
    }
    return null;
  };

  return text.replace(/\]\(([^)\s#]+)([^)]*)\)/g, (match, target, rest) => {
    if (/^(https?:|mailto:|#|\/)/.test(target)) return match;
    const to = moved(target);
    if (!to) return match;
    const relative = posix.relative(toDir, to.replace(/\/$/, '')) + (to.endsWith('/') ? '/' : '');
    return relative === target ? match : `](${relative}${rest})`;
  });
}

export function render(text, { path, config, manifest, payload }) {
  let out = text;

  // Longest first, so `docs/18-Board.md` is not clipped by a `docs/` prefix rule.
  const paths = payload.map((item) => item.path).sort((a, b) => b.length - a.length);
  for (const kitPath of paths) {
    const to = dest(kitPath, config, manifest);
    if (to !== kitPath) out = out.split(kitPath).join(to);
  }

  for (const [key, value] of Object.entries(config)) {
    if (typeof value === 'string' || typeof value === 'number') {
      out = out.split(`{{${key}}}`).join(String(value));
    }
  }

  if (out.includes(BLOCK)) return out;
  const board = `${config.boardDir}/cli.mjs`;
  const facts = [
    `- Kit: \`${config.kitDir}/\` · Tasks: \`${config.tasksDir}/\` · Roadmap: \`${config.roadmap}\``,
    config.conventionsDoc ? `- Conventions: \`${config.conventionsDoc}\`` : null,
    `- Integration branch: \`${config.integrationBranch}\` · Branch naming: \`${config.branchPattern}\` · Parallelism cap: ${config.parallelismCap}`,
    config.serializationPoints.length
      ? `- Serialization points: ${config.serializationPoints.map((point) => `\`${point}\``).join(', ')}`
      : null,
    `- Board: \`node ${board} …\` (${config.dataDir}/)`,
  ].filter(Boolean).join('\n');

  return `${out.trimEnd()}\n\n${BLOCK}\n${facts}\n`;
}

export const isRendered = (path) => path.startsWith('.claude/');
