// Executable forms (.claude/**) are rendered once, from the kit's own copies.
// Rendering is mechanical: rewrite the paths the kit names, then state the
// project's facts in one clearly-marked block. Prose is never rewritten.
import { dest } from './manifest.mjs';

const BLOCK = '## Project context (generated by devos install — edit freely, never regenerated)';

export function render(text, { path, config, manifest, payload }) {
  let out = text;

  // Longest first, so `docs/18-Board.md` is not clipped by a `docs/` prefix rule.
  const paths = payload.map((item) => item.path).sort((a, b) => b.length - a.length);
  for (const kitPath of paths) {
    const to = dest(kitPath, config, manifest);
    if (to !== kitPath) out = out.split(kitPath).join(to);
  }

  for (const [key, value] of Object.entries(config)) {
    if (typeof value === 'string' || typeof value === 'number') {
      out = out.split(`{{${key}}}`).join(String(value));
    }
  }

  if (out.includes(BLOCK)) return out;
  const board = `${config.boardDir}/cli.mjs`;
  const facts = [
    `- Kit: \`${config.kitDir}/\` · Tasks: \`${config.tasksDir}/\` · Roadmap: \`${config.roadmap}\``,
    config.conventionsDoc ? `- Conventions: \`${config.conventionsDoc}\`` : null,
    `- Integration branch: \`${config.integrationBranch}\` · Branch naming: \`${config.branchPattern}\` · Parallelism cap: ${config.parallelismCap}`,
    config.serializationPoints.length
      ? `- Serialization points: ${config.serializationPoints.map((point) => `\`${point}\``).join(', ')}`
      : null,
    `- Board: \`node ${board} …\` (${config.dataDir}/)`,
  ].filter(Boolean).join('\n');

  return `${out.trimEnd()}\n\n${BLOCK}\n${facts}\n`;
}

export const isRendered = (path) => path.startsWith('.claude/');
